enableInlineBuilds: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"

supportedArchitectures:
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.0.0-rc.49.cjs
